packages:
  - "playground"

allowBuilds:
  sharp: true
  unrs-resolver: true

enablePrePostScripts: true

onlyBuiltDependencies:
  - sharp
  - unrs-resolver

overrides:
  '@kinde-oss/kinde-auth-nextjs': 'link:'
